import type { Metadata } from 'next'
import './globals.css'
import { roboto } from '@lib/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} xl:max-w-[1440px] w-full m-auto`}>
        {children}
      </body>
    </html>
  )
}
